# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Generator
      module Column
        def add_column: (Postgres::Server::Database::Schema::Table::Column column, ?String? code_comment) -> Fragment
        def change_column: (Postgres::Server::Database::Schema::Table::Column column, ?String? code_comment) -> Fragment
        def remove_column: (Postgres::Server::Database::Schema::Table::Column column, ?String? code_comment) -> Fragment
        def set_column_comment: (Postgres::Server::Database::Schema::Table::Column column, ?String? code_comment) -> Fragment
        def remove_column_comment: (Postgres::Server::Database::Schema::Table::Column column, ?String? code_comment) -> Fragment

        # these come from the generator object (which this module is included into)
        def add_fragment: (migration_method: Symbol, object: untyped, migration: String, ?schema: Server::Database::Schema?, ?table: Server::Database::Schema::Table?, ?code_comment: String?, ?dependent_table: Server::Database::Schema::Table?) -> untyped

        def indent: (String migration, ?Integer levels) -> String

        class NoColumnCommentError < StandardError
        end
      end
    end
  end
end