# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Generator
      module ConstraintComments
        def set_validation_comment: (Postgres::Server::Database::Schema::Table::Validation validation) -> String
        def remove_validation_comment: (Postgres::Server::Database::Schema::Table::Validation validation) -> String

        def set_foreign_key_constraint_comment: (Postgres::Server::Database::Schema::Table::ForeignKeyConstraint foreign_key_constraint) -> String
        def remove_foreign_key_constraint_comment: (Postgres::Server::Database::Schema::Table::ForeignKeyConstraint foreign_key_constraint) -> String

        def set_unique_constraint_comment: (Postgres::Server::Database::Schema::Table::UniqueConstraint unique_constraint) -> String
        def remove_unique_constraint_comment: (Postgres::Server::Database::Schema::Table::UniqueConstraint unique_constraint) -> String

        # these come from the generator object (which this module is included into)
        def add_migration: (Symbol schema_name, Symbol | nil table_name, Symbol migration_method, Symbol | nil object_name, String migration) -> String
        def indent: (String str) -> String
      end
    end
  end
end