# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Generator
      module FixIndentation
        def fix_indentation: (String heredoc) -> String
      end
    end
  end
end