# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Generator
      module ForeignKeyConstraint
        def add_foreign_key_constraint: (Postgres::Server::Database::Schema::Table::ForeignKeyConstraint foreign_key_constraint, ?String? code_comment) -> Fragment
        def remove_foreign_key_constraint: (Postgres::Server::Database::Schema::Table::ForeignKeyConstraint foreign_key_constraint, ?String? code_comment) -> Fragment
        def recreate_foreign_key_constraint: (Postgres::Server::Database::Schema::Table::ForeignKeyConstraint original_foreign_key_constraint, Postgres::Server::Database::Schema::Table::ForeignKeyConstraint updated_foreign_key_constraint) -> Array[Fragment]
        def set_foreign_key_constraint_comment: (Postgres::Server::Database::Schema::Table::ForeignKeyConstraint foreign_key_constraint, ?String? code_comment) -> Fragment
        def remove_foreign_key_constraint_comment: (Postgres::Server::Database::Schema::Table::ForeignKeyConstraint foreign_key_constraint, ?String? code_comment) -> Fragment

        # these come from the generator object (which this module is included into)
        def add_fragment: (migration_method: Symbol, object: untyped, migration: String, ?schema: Server::Database::Schema?, ?table: Server::Database::Schema::Table?, ?code_comment: String?, ?dependent_table: Server::Database::Schema::Table?) -> untyped

        def indent: (String migration, ?Integer levels) -> String
        end
    end
  end
end