# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Generator
      module Function
        def create_function: (Postgres::Server::Database::Schema::Function function) -> String
        def update_function: (Postgres::Server::Database::Schema::Function function) -> String
        def drop_function: (Postgres::Server::Database::Schema::Function function) -> String
        def set_function_comment: (Postgres::Server::Database::Schema::Function function) -> String
        def remove_function_comment: (Postgres::Server::Database::Schema::Function function) -> String

        # these come from the generator object (which this module is included into)
        def add_migration: (Symbol schema_name, Symbol | nil table_name, Symbol migration_method, Symbol | nil object_name, String migration) -> String

      end
    end
  end
end
