# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Generator
      module Function
        def create_function: (Postgres::Server::Database::Schema::Function function, ?String? code_comment) -> Fragment
        def update_function: (Postgres::Server::Database::Schema::Function function, ?String? code_comment) -> Fragment
        def drop_function: (Postgres::Server::Database::Schema::Function function, ?String? code_comment) -> Fragment
        def set_function_comment: (Postgres::Server::Database::Schema::Function function, ?String? code_comment) -> Fragment
        def remove_function_comment: (Postgres::Server::Database::Schema::Function function, ?String? code_comment) -> Fragment

        # these come from the generator object (which this module is included into)
        def add_fragment: (migration_method: Symbol, object: untyped, migration: String, ?schema: Server::Database::Schema?, ?table: Server::Database::Schema::Table?, ?code_comment: String?, ?dependent_table: Server::Database::Schema::Table?) -> untyped

        def indent: (String migration, ?Integer levels) -> String
      end
    end
  end
end
