# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Generator
      module Index
        def add_index: (Postgres::Server::Database::Schema::Table::Index index, ?String? code_comment) -> Fragment
        def remove_index: (Postgres::Server::Database::Schema::Table::Index index, ?String? code_comment) -> Fragment
        def recreate_index: (Postgres::Server::Database::Schema::Table::Index original_index, Postgres::Server::Database::Schema::Table::Index updated_index) -> Array[Fragment]
        def set_index_comment: (Postgres::Server::Database::Schema::Table::Index index, ?String? code_comment) -> Fragment
        def remove_index_comment: (Postgres::Server::Database::Schema::Table::Index index, ?String? code_comment) -> Fragment

        # these come from the generator object (which this module is included into)
        def add_fragment: (migration_method: Symbol, object: untyped, migration: String, ?schema: Server::Database::Schema?, ?table: Server::Database::Schema::Table?, ?code_comment: String?, ?dependent_table: Server::Database::Schema::Table?) -> untyped

        def indent: (String migration, ?Integer levels) -> String
        end
    end
  end
end