# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Generator
      module PrimaryKey
        def add_primary_key: (Postgres::Server::Database::Schema::Table::PrimaryKey primary_key, ?nil | String code_comment) -> Fragment
        def remove_primary_key: (Postgres::Server::Database::Schema::Table::PrimaryKey primary_key, ?nil | String code_comment) -> Fragment
        def recreate_primary_key: (Postgres::Server::Database::Schema::Table::PrimaryKey original_primary_key, Postgres::Server::Database::Schema::Table::PrimaryKey updated_primary_key) -> Array[Fragment]

        # these come from the generator object (which this module is included into)
        def add_fragment: (schema: Server::Database::Schema, migration_method: Symbol, object: untyped, migration: String, ?table: nil | Server::Database::Schema::Table, ?code_comment: nil | String, ?dependent_table: nil | Server::Database::Schema::Table) -> untyped
        def indent: (String str) -> String

      end
    end
  end
end