# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Generator
      class SchemaMigration < Migration
        def initialize: (Symbol schema_name) -> void

      end
    end
  end
end
