# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Generator
      module UniqueConstraint
        def add_unique_constraint: (Postgres::Server::Database::Schema::Table::UniqueConstraint unique_constraint, ?String? code_comment) -> Fragment
        def remove_unique_constraint: (Postgres::Server::Database::Schema::Table::UniqueConstraint unique_constraint, ?String? code_comment) -> Fragment
        def recreate_unique_constraint: (Postgres::Server::Database::Schema::Table::UniqueConstraint original_unique_constraint, Postgres::Server::Database::Schema::Table::UniqueConstraint updated_unique_constraint) -> Array[Fragment]
        def set_unique_constraint_comment: (Postgres::Server::Database::Schema::Table::UniqueConstraint unique_constraint, ?String? code_comment) -> Fragment
        def remove_unique_constraint_comment: (Postgres::Server::Database::Schema::Table::UniqueConstraint unique_constraint, ?String? code_comment) -> Fragment

        # these come from the generator object (which this module is included into)
        def add_fragment: (migration_method: Symbol, object: untyped, migration: String, ?schema: Server::Database::Schema?, ?table: Server::Database::Schema::Table?, ?code_comment: String?, ?dependent_table: Server::Database::Schema::Table?) -> untyped

        def indent: (String migration, ?Integer levels) -> String
        end
    end
  end
end