# TypeProf 0.21.7

# Classes
module DynamicMigrations
  class Generator
    module Index
      def add_index: (untyped index) -> untyped
      def remove_index: (untyped index) -> untyped

      # these come from the generator object (which this module is included into)
      def add_migration: (Symbol schema_name, Symbol table_name, String name, String sql) -> String
    end
  end
end
