# TypeProf 0.21.7

# Classes
module DynamicMigrations
  class Generator
    module Schema
      def create_schema: (Postgres::Server::Database::Schema schema) -> String
      def drop_schema: (Postgres::Server::Database::Schema schema) -> String

      # these come from the generator object (which this module is included into)
      def add_migration: (Symbol schema_name, nil table_name, String name, String sql) -> String
    end
  end
end
