# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Generator
      class SchemaMigrations
        class Section
          attr_reader schema_name: Symbol
          attr_reader table_name: Symbol | nil
          attr_reader content_type: Symbol
          attr_reader object_name: Symbol | nil
          attr_reader content: String

          def initialize: (Symbol schema_name, Symbol | nil table_name, Symbol content_type, Symbol | nil object_name, String content) -> void
          def content_type?: (Symbol content_type) -> bool
        end
      end
    end
  end
end
