module DynamicMigrations
  module ActiveRecord
    module Migrators
      include Validation
      include ForeignKeyConstraint
      include Column
      include Table
      include Index
      include Function
      include Trigger

      def self.included: (untyped base) -> void
      def quote: (untyped string) -> String
      def schema_name: -> Symbol
      def self.schema_name: -> Symbol

      # this methods comes from active record once the module has been included
      def connection: -> untyped

      class SchemaNameNotSetError < StandardError
      end

      class DeferrableOptionsError < StandardError
      end

      class MissingFunctionBlockError < StandardError
      end

      module ClassMethods
        @current_schema: Symbol?

        def schema_name: -> Symbol?
        def set_schema_name: (untyped schema_name) -> void
        def clear_schema_name: -> void
      end
    end
  end
end
