# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module ActiveRecord
    module Migrators
      self.@current_schema: nil

      include Validation
      include ForeignKeyConstraint
      include Column
      include Table
      include Index
      include Function
      include Trigger

      def self.schema_name: -> nil
      def self.set_schema_name: (untyped schema_name) -> untyped
      def self.clear_schema_name: -> nil
      def self.included: (untyped klass) -> untyped
      def schema_name: -> nil

      # this methods comes from active record once the module has been included
      def connection: -> untyped

      class SchemaNameNotSetError < StandardError
      end

      class DeferrableOptionsError < StandardError
      end

      class MissingFunctionBlockError < StandardError
      end
    end
  end
end
