# frozen_string_literal: true

require "pg"

require "dynamic_migrations/version"
require "dynamic_migrations/invalid_source_error"
require "dynamic_migrations/expected_symbol_error"
require "dynamic_migrations/expected_string_error"
require "dynamic_migrations/expected_integer_error"
require "dynamic_migrations/expected_boolean_error"
require "dynamic_migrations/module_included_into_unexpected_target_error"

require "dynamic_migrations/postgres/server/database/connection"
require "dynamic_migrations/postgres/server/database/structure_loader"
require "dynamic_migrations/postgres/server/database/validations_loader"
require "dynamic_migrations/postgres/server/database/keys_and_unique_constraints_loader"
require "dynamic_migrations/postgres/server/database/triggers_and_functions_loader"
require "dynamic_migrations/postgres/server/database/loaded_schemas_builder"
require "dynamic_migrations/postgres/server/database/loaded_schemas"
require "dynamic_migrations/postgres/server/database/configured_schemas"

require "dynamic_migrations/postgres/server/database/differences"
require "dynamic_migrations/postgres/server/database/differences/to_migrations/schemas"
require "dynamic_migrations/postgres/server/database/differences/to_migrations/schema/tables"
require "dynamic_migrations/postgres/server/database/differences/to_migrations/schema/functions"
require "dynamic_migrations/postgres/server/database/differences/to_migrations"

require "dynamic_migrations/postgres/server/database"
require "dynamic_migrations/postgres/server/database/source"

require "dynamic_migrations/postgres/server/database/schema/tables"
require "dynamic_migrations/postgres/server/database/schema/functions"
require "dynamic_migrations/postgres/server/database/schema"
require "dynamic_migrations/postgres/server/database/schema/function"
require "dynamic_migrations/postgres/server/database/schema/table/validations"
require "dynamic_migrations/postgres/server/database/schema/table/indexes"
require "dynamic_migrations/postgres/server/database/schema/table/foreign_key_constraints"
require "dynamic_migrations/postgres/server/database/schema/table/unique_constraints"
require "dynamic_migrations/postgres/server/database/schema/table/columns"
require "dynamic_migrations/postgres/server/database/schema/table/triggers"
require "dynamic_migrations/postgres/server/database/schema/table"
require "dynamic_migrations/postgres/server/database/schema/table/column"
require "dynamic_migrations/postgres/server/database/schema/table/validation"
require "dynamic_migrations/postgres/server/database/schema/table/foreign_key_constraint"
require "dynamic_migrations/postgres/server/database/schema/table/index"
require "dynamic_migrations/postgres/server/database/schema/table/primary_key"
require "dynamic_migrations/postgres/server/database/schema/table/trigger"
require "dynamic_migrations/postgres/server/database/schema/table/unique_constraint"

require "dynamic_migrations/postgres/server"
require "dynamic_migrations/postgres/connections"

require "dynamic_migrations/postgres/generator/schema"
require "dynamic_migrations/postgres/generator/table"
require "dynamic_migrations/postgres/generator/column"
require "dynamic_migrations/postgres/generator/foreign_key_constraint"
require "dynamic_migrations/postgres/generator/function"
require "dynamic_migrations/postgres/generator/index"
require "dynamic_migrations/postgres/generator/primary_key"
require "dynamic_migrations/postgres/generator/trigger"
require "dynamic_migrations/postgres/generator/unique_constraint"
require "dynamic_migrations/postgres/generator/validation"
require "dynamic_migrations/postgres/generator/fix_indentation"
require "dynamic_migrations/postgres/generator"
require "dynamic_migrations/postgres/generator/schema_migrations"
require "dynamic_migrations/postgres/generator/schema_migrations/section"

require "dynamic_migrations/active_record/migrators/schema"
require "dynamic_migrations/active_record/migrators/check_constraint"
require "dynamic_migrations/active_record/migrators/foreign_key_constraint"
require "dynamic_migrations/active_record/migrators/unique_constraint"
require "dynamic_migrations/active_record/migrators/function"
require "dynamic_migrations/active_record/migrators/trigger"
require "dynamic_migrations/active_record/migrators/constraint_comment"
require "dynamic_migrations/active_record/migrators"

module DynamicMigrations
end
