module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Schema
          class Table
            class Column < Source
              attr_reader table: Table
              attr_reader name: Symbol
              attr_reader description: String?
              attr_reader null: bool
              attr_reader default: untyped
              attr_reader data_type: Symbol
              attr_reader array: bool
              attr_reader interval_type: Symbol?
              attr_reader enum: Enum?

              def initialize: (database_or_configuration source, Table table, Symbol name, Symbol data_type, ?null: bool, ?default: untyped, ?description: String?, ?interval_type: Symbol?, ?enum: Enum?) -> void
              def has_description?: -> bool
              def array?: -> bool

              class ExpectedTableError < StandardError
              end

              class UnexpectedEnumError < StandardError
              end
            end
          end
        end
      end
    end
  end
end
