module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Schema
          class Table
            module Indexes
              @indexes: Hash[Symbol, Index]

              def index: (Symbol name) -> Index
              def has_index?: (Symbol name) -> bool
              def indexes: -> Array[Index]
              def indexes_hash: -> Hash[Symbol, Index]
              def add_index: (Symbol name, Array[Symbol] column_names, ?include_column_names: Array[Symbol], **untyped) -> Index

              # these come from the table object (which this module is included into)
              def source: -> database_or_configuration
              def column: (Symbol column_name) -> Column

              class IndexDoesNotExistError < StandardError
              end

              class IndexAlreadyExistsError < StandardError
              end
            end
          end
        end
      end
    end
  end
end
