module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Schema
          class Table
            class PrimaryKey < Source
              @columns: Hash[Symbol, Column]

              attr_reader table: Table
              attr_reader name: Symbol
              attr_reader description: String?

              def initialize: (database_or_configuration source, Table table, Array[Column] columns, Symbol name, ?description: String?) -> void
              def columns: -> Array[Column]
              def column_names: -> Array[Symbol]
              def has_description?: -> bool
              def differences_descriptions: (PrimaryKey other_primary_key) -> Array[String]

              private
              def add_column: (Column column) -> void

              class ExpectedTableError < StandardError
              end

              class ExpectedArrayOfColumnsError < StandardError
              end

              class UnexpectedIndexTypeError < StandardError
              end

              class DuplicateColumnError < StandardError
              end

              class InvalidNameError < StandardError
              end
            end
          end
        end
      end
    end
  end
end
