module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Schema
          class Table
            class PrimaryKey < Source
              @columns: Hash[Symbol, Column]

              attr_reader table: Table
              attr_reader name: Symbol
              attr_reader description: String | nil

              def initialize: (database_or_configuration source, Table table, Array[Column] columns, Symbol name, ?description: String | nil) -> void
              def columns: -> Array[Column]

              private
              def add_column: (Column column) -> void

              class ExpectedTableError < StandardError
              end

              class ExpectedArrayOfColumnsError < StandardError
              end

              class UnexpectedIndexTypeError < StandardError
              end

              class DuplicateColumnError < StandardError
              end
            end
          end
        end
      end
    end
  end
end
