# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Schema
          class Table
            class Trigger < Source
              @action_order: Integer?
              attr_reader table: Table
              attr_reader name: Symbol
              attr_reader event_manipulation: Symbol
              attr_reader action_timing: Symbol
              attr_reader action_condition: String?
              attr_reader parameters: Array[String]
              attr_reader action_orientation: Symbol
              attr_reader function: Function
              attr_reader action_reference_old_table: Symbol?
              attr_reader action_reference_new_table: Symbol?
              attr_reader description: String?
              attr_reader template: Symbol?

              def initialize: (database_or_configuration source, Table table, Symbol name, action_timing: Symbol, event_manipulation: Symbol, parameters: Array[String], action_orientation: Symbol, function: Function, ?action_order: Integer?, ?action_condition: String?, ?action_reference_old_table: Symbol?, ?action_reference_new_table: Symbol?, ?description: String?, ?template: Symbol?) -> void
              def action_order: -> Integer
              def has_description?: -> false
              def differences_descriptions: (Trigger other_trigger) -> Array[String]

              class ExpectedTableError < StandardError
              end

              class UnexpectedEventManipulationError < StandardError
              end

              class UnexpectedParametersError < StandardError
              end

              class UnexpectedActionOrientationError < StandardError
              end

              class UnexpectedActionTimingError < StandardError
              end

              class ExpectedOldRecordsTableError < StandardError
              end

              class ExpectedNewRecordsTableError < StandardError
              end

              class ExpectedFunctionError < StandardError
              end

              class UnexpectedActionOrderError < StandardError
              end

              class UnexpectedTemplateError < StandardError
              end
            end
          end
        end
      end
    end
  end
end
