module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Schema
          class Table
            class UniqueConstraint < Source
              INDEX_TYPES: [:btree, :hash, :gist, :gin, :bring, :spgist]
              @columns: Hash[Symbol, Column]

              attr_reader table: Table
              attr_reader name: Symbol
              attr_reader deferrable: bool
              attr_reader initially_deferred: bool
              attr_reader description: String?

              def initialize: (database_or_configuration source, Table table, Array[Column] columns, Symbol name, ?deferrable: bool, ?initially_deferred: bool, ?description: String?) -> void
              def columns: -> Array[Column]
              def column_names: -> Array[Symbol]
              def has_description?: -> bool
              def differences_descriptions: (UniqueConstraint other_unique_constraint) -> Array[String]

              private
              def add_column: (Column column) -> void

              class ExpectedTableError < StandardError
              end

              class ExpectedArrayOfColumnsError < StandardError
              end

              class UnexpectedIndexTypeError < StandardError
              end

              class UnexpectedOrderError < StandardError
              end

              class UnexpectedNullsPositionError < StandardError
              end

              class DuplicateColumnError < StandardError
              end

              class InvalidNameError < StandardError
              end
            end
          end
        end
      end
    end
  end
end
