module DynamicMigrations
  module Postgres
    class Server
      class Database
        @configured_schemas: Hash[Symbol, Schema]
        @loaded_schemas: Hash[Symbol, Schema]
        @configured_extensions: Hash[Symbol, true]
        @loaded_extensions: Hash[Symbol, true]

        include Connection
        include StructureLoader
        include ValidationsLoader
        include KeysAndUniqueConstraintsLoader
        include TriggersAndFunctionsLoader
        include LoadedSchemas
        include ConfiguredSchemas
        include LoadedSchemasBuilder
        include ConfiguredExtensions
        include LoadedExtensions
        include EnumsLoader
        include ExtensionsLoader

        attr_reader server: Server
        attr_reader name: Symbol
        def initialize: (Server server, Symbol name) -> void
        def schema: (Symbol schema_name, database_or_configuration source) -> untyped
        def differences: -> Differences

        class ExpectedServerError < StandardError
        end
      end
    end
  end
end
