# TypeProf 0.21.7

# Classes
module DynamicMigrations
  class Generator
    @migrations: Hash[Symbol, Hash[Symbol, Hash[String, String]]]

    include Schema
    include Table
    include Column
    include ForeignKeyConstraint
    include Index
    include PrimaryKey
    include UniqueConstraint
    include Validation
    include FixIndentation

    def initialize: -> void
    def schema_migrations: (Symbol schema_name) -> Array[Hash[Symbol, String]]

    private
    def add_migration: (Symbol schema_name, Symbol table_name, String migration_name, String migration) -> String

    class ExpectedSymbolError < StandardError
    end

    class DeferrableOptionsError < StandardError
    end

  end
end
