# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Differences
          class ToMigrations
            module Extensions

              private
              def process_extension: (Symbol extension_name, untyped configuration_extension, untyped database_extension) -> void


            end
          end
        end
      end
    end
  end
end