# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Differences
          class ToMigrations
            module Schemas

              private
              def process_schema: (Symbol schema_name, untyped configuration_schema, untyped database_schema) -> void

              # this method comes from the Functions module
              def process_functions: (Symbol schema_name, untyped configuration_functions, untyped database_functions) -> void

              # this method comes from the Enums module
              def process_enums: (Symbol schema_name, untyped configuration_enums, untyped database_enums) -> void

              # this method comes from the Tables module
              def process_tables: (Symbol schema_name, untyped configuration_tables, untyped database_tables) -> void

              # this method is available on the ToMigrations class which includes this module
              def log: -> Logging::Logger

            end
          end
        end
      end
    end
  end
end