# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Schema
          class Enum < Source
            attr_reader schema: Schema
            attr_reader name: Symbol
            attr_reader values: Array[String]
            attr_reader description: String?
            attr_reader columns: Array[Table::Column]
            def initialize: (database_or_configuration source, Schema schema, Symbol name, Array[String] values, ?description: String?) -> void
            def full_name: -> Symbol
            def has_description?: -> bool
            def add_column: (Schema::Table::Column column) -> void
            def differences_descriptions: (Enum other_enum) -> Array[String]

            class ExpectedSchemaError < StandardError
            end

            class ExpectedValuesError < StandardError
            end
          end
        end
      end
    end
  end
end
