# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Schema
          class Function < Source
            attr_reader schema: untyped
            attr_reader name: untyped
            attr_reader definition: untyped
            attr_reader description: nil
            attr_reader triggers: Array[Schema::Table::Trigger]
            def initialize: (untyped source, untyped schema, untyped name, untyped definition, ?description: nil) -> void
            def has_description?: -> false
            def add_trigger: (Schema::Table::Trigger trigger) -> void
            def differences_descriptions: (Function other_function) -> Array[String]

            class ExpectedSchemaError < StandardError
            end

            class ExpectedDefinitionError < StandardError
            end
          end
        end
      end
    end
  end
end
