# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Schema
          module Functions
            @functions: Hash[untyped, untyped]

            def add_function: (untyped function_name, untyped definition, ?description: nil) -> nil
            def function: (untyped function_name) -> untyped
            def has_function?: (untyped function_name) -> bool
            def functions: -> Array[untyped]
            def functions_hash: -> Hash[untyped, untyped]

            # these come from the schema object (which this module is included into)
            def source: -> database_or_configuration

            class FunctionAlreadyExistsError < StandardError
            end

            class FunctionDoesNotExistError < StandardError
            end
          end
        end
      end
    end
  end
end
