# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Schema
          module Functions
            @functions: Hash[Symbol, Function]

            def add_function: (Symbol function_name, String definition, ?description: String?) -> nil
            def function: (Symbol function_name) -> Function
            def has_function?: (Symbol function_name) -> bool
            def functions: -> Array[Function]
            def functions_hash: -> Hash[Symbol, Function]

            # these come from the schema object (which this module is included into)
            def source: -> database_or_configuration

            class FunctionAlreadyExistsError < StandardError
            end

            class FunctionDoesNotExistError < StandardError
            end
          end
        end
      end
    end
  end
end
