# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module ActiveRecord
    module Migrators
      module Index
        def set_index_comment: (Symbol table_name, Symbol index_name, String comment) -> void
        def remove_index_comment: (Symbol table_name, Symbol index_name) -> void

        # stubbing these out, as they are available on the module which includes this module
        def execute: (String sql) -> void
        def quote: (String str) -> String
      end
    end
  end
end
