# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module ActiveRecord
    module Migrators
      module Schema
        def create_schema: (untyped schema_name) -> untyped
        def drop_schema: (untyped schema_name) -> untyped
      end
    end
  end
end
