# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module ActiveRecord
    module Migrators
      module Schema
        def create_schema: () -> void
        def drop_schema: () -> void

        # stubbing these out, as they are available on the module which includes this module
        def execute: (String sql) -> void
        def schema_name: () -> Symbol
      end
    end
  end
end
