# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module ActiveRecord
    module Migrators
      module TableComment
        def set_table_comment: (Symbol table_name, String comment) -> void
        def remove_table_comment: (Symbol table_name) -> void

        # stubbing these out, as they are available on the module which includes this module
        def execute: (String sql) -> void
        def schema_name: () -> Symbol
        def quote: (String str) -> String
      end
    end
  end
end
