# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module ActiveRecord
    module Migrators
      module UniqueConstraint
        def add_unique_constraint: (Symbol table_name, Array[Symbol] column_names, name: Symbol, ?deferrable: bool, ?initially_deferred: bool, ?comment: nil | String) -> void

        # stubbing these out, as they are available on the module which includes this module
        def set_constraint_comment: (Symbol table_name, Symbol constraint_name, String comment) -> void
        def execute: (String sql) -> void
      end
    end
  end
end
