# TypeProf 0.21.7

# Classes
module DynamicMigrations
  module ActiveRecord
    module Migrators
      module UniqueConstraint
        def add_unique_constraint: (Symbol table_name, Array[Symbol] column_names, name: Symbol, ?deferrable: bool, ?initially_deferred: bool, ?comment: String?) -> void
        def remove_unique_constraint: (Symbol table_name, Symbol name) -> void
        def set_unique_constraint_comment: (Symbol table_name, Symbol unique_constraint_name, String comment) -> void
        def remove_unique_constraint_comment: (Symbol table_name, Symbol unique_constraint_name) -> void

        # stubbing these out, as they are available on the module which includes this module
        def execute: (String sql) -> void
        def schema_name: () -> Symbol
        def quote: (String str) -> String
      end
    end
  end
end
