module DynamicMigrations
  module Postgres
    class Server
      class Database
        module Connection
          @connection: PG::Connection | nil

          def connect: -> PG::Connection
          def connection: -> PG::Connection
          def disconnect: -> void
          def with_connection: -> void

          # these come from the database object (which this module is included into)
          def name: -> Symbol
          def server: -> Server

          class NotConnectedError < StandardError
          end

          class MissingDatabaseNameError < StandardError
          end

          class AlreadyConnectedError < StandardError
          end
        end
      end
    end
  end
end
