module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Differences
          @database: Database

          def initialize: (Database database) -> void
          def to_h: -> {
            configuration: Hash[Symbol, untyped],
            database: Hash[Symbol, untyped]
          }
          def self.compare_schemas: (Hash[Symbol, Schema] schemas, Hash[Symbol, Schema] comparison_schemas) -> Hash[Symbol, untyped]
          def self.compare_schema: (Schema schema, Schema comparison_schema) -> {
            exists: true,
            tables: Hash[Symbol, untyped]
          }
          def self.compare_tables: (Hash[Symbol, Schema::Table] tables, Hash[Symbol, Schema::Table] comparison_tables) -> Hash[Symbol, untyped]
          def self.compare_table: (Schema::Table table, Schema::Table comparison_table) -> Hash[Symbol, untyped]
          def self.compare_columns: (Hash[Symbol, Schema::Table::Column] columns, Hash[Symbol, Schema::Table::Column] comparison_columns) -> Hash[Symbol, untyped]
          def self.compare_unique_constraints: (Hash[Symbol, Schema::Table::UniqueConstraint] unique_constraints, Hash[Symbol, Schema::Table::UniqueConstraint] comparison_unique_constraints) -> Hash[Symbol, untyped]
          def self.compare_indexes: (Hash[Symbol, Schema::Table::Index] indexes, Hash[Symbol, Schema::Table::Index] comparison_indexes) -> Hash[Symbol, untyped]
          def self.compare_validations: (Hash[Symbol, Schema::Table::Validation] validations, Hash[Symbol, Schema::Table::Validation] comparison_validations) -> Hash[Symbol, untyped]
          def self.compare_foreign_key_constraints: (Hash[Symbol, Schema::Table::ForeignKeyConstraint] foreign_key_constraints, Hash[Symbol, Schema::Table::ForeignKeyConstraint] comparison_foreign_key_constraints) -> Hash[Symbol, untyped]
          def self.compare_record: (Object | nil base, Object | nil comparison, Array[Symbol] method_list) -> Hash[Symbol, untyped]

          class ExpectedDatabaseError < StandardError
          end

          class TableRequiredError < StandardError
          end

          class SchemaRequiredError < StandardError
          end
        end
      end
    end
  end
end
