module DynamicMigrations
  module Postgres
    class Server
      class Database
        module KeysAndUniqueConstraintsLoader
          def create_database_keys_and_unique_constraints_cache: -> void
          def fetch_keys_and_unique_constraints: -> Hash[untyped, untyped]
          def refresh_database_keys_and_unique_constraints_cache: -> void

          # these come from the database object (which this module is included into)
          def connection: -> PG::Connection
        end
      end
    end
  end
end
