module DynamicMigrations
  module Postgres
    class Server
      class Database
        class Schema < Source
          include Functions
          include Tables

          attr_reader database: Database
          attr_reader name: Symbol
          def initialize: (database_or_configuration source, Database database, Symbol name) -> void

          class ExpectedDatabaseError < StandardError
          end

        end
      end
    end
  end
end
