module DynamicMigrations
  module Postgres
    class Server
      class Database
        module StructureLoader
          def create_database_structure_cache: -> void
          def fetch_structure: -> Hash[untyped, untyped]
          def recursively_load_database_structure: -> void
          def fetch_schema_names: -> Array[String]
          def fetch_table_names: (Symbol schema_name) -> Array[String]

          # these come from the database object (which this module is included into)
          def connection: -> PG::Connection
          def add_loaded_schema: (Symbol schema_name) -> untyped
        end
      end
    end
  end
end
